# Generated by Django 4.2.15 on 2024-08-26 05:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestRun",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateField()),
                ("end_time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[1402, 1000],
                        upload_to="runMain",
                    ),
                ),
                (
                    "route_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[1402, 1402],
                        upload_to="runRoute",
                    ),
                ),
                ("start_point", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ST1", "대기중"),
                            ("ST2", "판매중"),
                            ("ST3", "판매 종료"),
                            ("ST4", "이벤트 D-day"),
                            ("ST5", "이벤트 종료"),
                        ],
                        default="ST1",
                        max_length=3,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Level-1, 800", "800"),
                            ("Level-2, 730", "730"),
                            ("Level-3, 700", "700"),
                            ("Level-4, 630", "630"),
                            ("Level-5, 600", "600"),
                            ("Level-6, 530", "530"),
                            ("Free", "Free"),
                        ],
                        default="Free",
                        max_length=15,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("route", models.CharField(max_length=50)),
                ("desc", models.TextField(blank=True, default="-")),
                ("completed", models.BooleanField(default=False)),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager",
                        to="community.manager",
                    ),
                ),
            ],
        ),
    ]
