# Generated by Django 4.2.15 on 2024-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_guestrun_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestrun",
            name="level",
            field=models.CharField(
                choices=[
                    ("Level-1, 800", "800"),
                    ("Level-2, 730", "730"),
                    ("Level-3, 700", "700"),
                    ("Level-4, 630", "630"),
                    ("Level-5, 600", "600"),
                    ("Level-6, 530", "530"),
                    ("Full Access", "Free"),
                ],
                default="Free",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="guestrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("Checking", "대기중"),
                    ("On Sale", "판매중"),
                    ("Sold Out", "판매 종료"),
                    ("Closed", "이벤트 종료"),
                ],
                default="Checking",
                max_length=8,
            ),
        ),
    ]
