# Generated by Django 4.2.15 on 2024-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_guestrun_level_alter_guestrun_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("Checking", "대기중"),
                    ("On-Sale", "판매중"),
                    ("Sold-Out", "판매 종료"),
                    ("Closed", "이벤트 종료"),
                ],
                default="Checking",
                max_length=8,
            ),
        ),
    ]
