# Generated by Django 4.2.15 on 2024-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_guestrun_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("ST1", "Checking"),
                    ("ST2", "On-Sale"),
                    ("ST3", "Sold-Out"),
                    ("ST4", "Closed"),
                ],
                default="ST2",
                max_length=8,
            ),
        ),
    ]
