# Generated by Django 4.2.15 on 2024-08-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_guestrun_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestrun",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guestrun",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guestrun",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
