# Generated by Django 4.2.15 on 2024-09-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_guestrun_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestrun",
            name="lang",
            field=models.CharField(
                choices=[
                    ("KO", "Korean"),
                    ("EN", "English"),
                    ("JP", "Japanese"),
                    ("CN", "Chinese"),
                ],
                default="KO",
                max_length=10,
            ),
        ),
    ]
