# Generated by Django 4.2.15 on 2024-09-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_alter_guestrun_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestrun",
            name="map_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
