# Generated by Django 4.2.15 on 2024-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_guestrun_map_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestrun",
            name="participant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
