# Generated by Django 4.2.15 on 2024-10-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0017_guestrun_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Days",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reservation_id", models.CharField(max_length=50)),
                ("participant", models.CharField(max_length=20)),
                ("date", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.guestrun",
                    ),
                ),
            ],
        ),
    ]
