# Generated by Django 4.2.15 on 2024-10-10 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("scalendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="days",
            name="d_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="days",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
