# Generated by Django 4.2.15 on 2024-08-26 05:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "reserv_id",
                    models.CharField(
                        default="Required_pk",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                (
                    "start_time",
                    models.TimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("end_date", models.DateField()),
                (
                    "end_time",
                    models.TimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("image", models.ImageField(blank=True, upload_to="reservation")),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ST1", "예약 양식 제출 완료"),
                            ("ST2", "예약 완료 및 결제 대기"),
                            ("ST3", "결제 완료"),
                            ("ST4", "배송 중"),
                            ("ST5", "배송 완료"),
                            ("ST6", "반납 완료"),
                            ("ST7", "입고 완료"),
                        ],
                        default="ST1",
                        max_length=3,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("paypal_link", models.CharField(default="-", max_length=50)),
                ("delivery", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                (
                    "bag",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "bag"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bagName",
                        to="items.item",
                    ),
                ),
                (
                    "bottom",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "bottom"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bottomName",
                        to="items.item",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.guestrun",
                    ),
                ),
                (
                    "shoes",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "shoes"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shoesName",
                        to="items.item",
                    ),
                ),
                (
                    "top",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "top"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topName",
                        to="items.item",
                    ),
                ),
            ],
        ),
    ]
