# Generated by Django 4.2.15 on 2024-08-28 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="event_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="event_time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
