# Generated by Django 4.2.15 on 2024-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_reservation_event_date_reservation_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
