# Generated by Django 4.2.15 on 2024-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_alter_reservation_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
