# Generated by Django 4.2.15 on 2024-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0004_alter_reservation_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="event_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
