# Generated by Django 4.2.15 on 2024-08-26 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "q_id",
                    models.CharField(
                        default="Required_pk",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CG1", "About Event"),
                            ("CG2", "About Rental Items"),
                            ("CG3", "About Business"),
                            ("CG4", "Others"),
                        ],
                        default="CG1",
                        max_length=20,
                    ),
                ),
                ("shortq", models.TextField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "m_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("age", models.IntegerField(default=0)),
                ("image", models.ImageField(blank=True, upload_to="avatar")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
