# Generated by Django 4.2.15 on 2024-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="m_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
