# Generated by Django 4.2.15 on 2024-08-26 06:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_manager_m_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[200, 200],
                upload_to="avatar",
            ),
        ),
    ]
