# Generated by Django 4.2.15 on 2024-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shoes", "Shoes"),
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("bag", "Bag & Pouch"),
                            ("etc", "ETC"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Female"), ("E", "NO Gender"), ("M", "Male")],
                        max_length=1,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20)),
                (
                    "model_num",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Others", "free"),
                            (
                                "shoes",
                                (
                                    ("220", "220mm"),
                                    ("225", "225mm"),
                                    ("230", "230mm"),
                                    ("235", "235mm"),
                                    ("240", "240mm"),
                                    ("245", "245mm"),
                                    ("250", "250mm"),
                                    ("255", "255mm"),
                                    ("260", "260mm"),
                                    ("265", "265mm"),
                                    ("270", "270mm"),
                                    ("275", "275mm"),
                                    ("280", "280mm"),
                                    ("285", "285mm"),
                                    ("290", "290mm"),
                                    ("295", "295mm"),
                                    ("300", "300mm"),
                                ),
                            ),
                            (
                                "top",
                                (
                                    ("XS", "XS"),
                                    ("S", "S"),
                                    ("M", "M"),
                                    ("L", "L"),
                                    ("XL", "XL"),
                                    ("XXL", "XXL"),
                                ),
                            ),
                            (
                                "bottom",
                                (
                                    ("XXS", "XXS"),
                                    ("XS", "XS"),
                                    ("S", "S"),
                                    ("M", "M"),
                                    ("L", "L"),
                                    ("XL", "XL"),
                                    ("XXL", "XXL"),
                                    ("3XL", "3XL"),
                                    ("4XL", "4XL"),
                                    ("5XL", "5XL"),
                                ),
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.IntegerField(blank=True, default=0)),
                ("link", models.URLField(blank=True)),
            ],
        ),
    ]
