# Generated by Django 4.2.15 on 2024-09-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_alter_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("E", "NO Gender"), ("M", "Male"), ("F", "Female")],
                max_length=1,
            ),
        ),
    ]
