# Generated by Django 5.1 on 2024-10-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_alter_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('E', 'NO Gender'), ('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
