# Generated by Django 5.1 on 2024-10-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0050_alter_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('E', 'NO Gender'), ('F', 'Female')], max_length=1),
        ),
    ]
